### ISSUE TITLE
AWS role for William and Alex

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-infra#2]

**Comment by Carolusian** [comment]
@guoliu this article is quite clear about the steps to create a sub-account in AWS: https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

If in any scenario that sharing access between accounts is necessary, then we may refer to:

- https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html
- https://tomgregory.com/cross-account-vpc-access-in-aws/
